import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
// import { CartProvider } from "react-use-cart";
import Footer from "@/components/Footer";
import CartProvider from "@/Providers/CartProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CartProvider>
          <Header />
          {children}
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
